{% set name = "SDL2_gfx" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/sdl2gfx/files/{{ name }}-{{ version }}.tar.gz
  sha256: 63e0e01addedc9df2f85b93a248f06e8a04affa014a835c2ea34bfe34e576262

build:
  number: 1

requirements:
  build:
    - cmake  # [win]
    - pkg-config  # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - gnuconfig   # [unix]
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sdl2

test:
  commands:
    - test -f $PREFIX/lib/libSDL2_gfx.a  # [unix]
    - test -f $PREFIX/lib/libSDL2_gfx${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\SDL2_gfx.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\SDL2_gfx.dll exit 1  # [win]

about:
  home: http://www.ferzkopp.net/wordpress/2016/01/02/sdl_gfx-sdl2_gfx/
  license: Zlib
  license_file: COPYING
  summary: "Graphics primitives and surface functions for SDL2"
  description: |
    The SDL2_gfx library provides the basic drawing functions such as lines, 
    circles or polygons provided by SDL_gfx on SDL2 against renderers of SDL2.
  doc_url: http://www.ferzkopp.net/Software/SDL2_gfx/Docs/html/index.html
  dev_url: https://sourceforge.net/projects/sdl2gfx/

extra:
  recipe-maintainers:
    - dschreij
