travis:
  secure:
    BINSTAR_TOKEN: causQXav5twIGnY8CEVztYNJQhUNUZzC8DL7hnbbCPUENuDxT4ptbrEoWzN33FSaxFMUP5WssZFhd5cauj8cqwjroGmp0fdnVmTrlMJJkLX9W9TSkcibNiEf0/u9Bco3KF25+K2LrcdnQ8cfkvl5uSinotMtB7aEFgcSPAeKKZY9uSA7iUE0nloR4OygfkucenQ+TD6HPPU9LoBPk1REMkyayu+6BUReYRZwEA1/vVwVYEol87jFgBtZO+bQvdYwn/Z9aZFzN5J6emtC0/fqANUknf09QiAPHwcfj2e8eYknP09BJqxfgy1bAZjdXYVkCrmvJszHJLDzsuMDjAq5DeCMXEW2HEjdbnFXHiKuEP5rDEQn/MffYKXha11xCl4n3Aq7kGt3B3vh3di4+Ws2yipntOhjQ+X4Tvq9SbE060tYuakGAxDlohbeaToNKvuJZJSnO6457keMErryoj5aDHosdoMxyrOU+Jq0YWDXGUvgaF9SYgM4J/e3LU0VPpxrEOV6bn1s/rjD52uil5ACIKLvBFn2gtEpb3+6fGJ6X6FdhNtSG6KWIClmDxxMDAKzwnV44vm8zNyPkgZpIH7tp4LBtBwt5SkoHmtyzACUeV/REEj7crMUdlTbcEjv6LD1zST7q6NsC9Ekv7zIBFOonE7BRhtHmx/Z5mwXFhmkQn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider: {win: azure}
conda_forge_output_validation: false
